### ISSUE TITLE
How do I format a JSON Abstracted Resource Object Property?

### ISSUE THREAD

**Issue by yumpy** [stevenjack/cfndsl#107]
I have a QueuePolicy resource which works well with cfndsl

```ruby
  Resource("sqspolicyEvents") do
    Type("AWS::SQS::QueuePolicy")
    Property("Queues", [
      Ref("queueEvents")
    ])
    Property("PolicyDocument", {
      "Statement" => [
        {
          "Action"    => ["SQS:SendMessage"],
          "Effect"    => "Allow",
          "Principal" => {"AWS" => [ "*"] },
          "Resource"  => [FnGetAtt("queueEvents", "Arn")],
          "Sid"       => "Sid1430973749198"
        }
      ]
    })
  end
```

I'm in the process of updating my 'code' to use the abstracted objects; eg:

```ruby
  QueuePolicy(:sqspolicyEvents) {
    Queues [ Ref("queueEvents") ]
    PolicyDocument {
      "Statement" => [
        {
          "Action"    => ["SQS:SendMessage"],
          "Effect"    => "Allow",
          "Principal" => {"AWS" => [ "*"] },
          "Resource"  => [FnGetAtt("queueEvents", "Arn")],
          "Sid"       => "Sid1430973749198"
        }
      ]
    }
  }
```

However I'm getting a syntax error: `syntax error, unexpected =>, expecting '}'`

What's the correct way to format a PolicyDocument? The definitions in aws_types.yaml indicates a Type of JSON but I've not been able to work out how to do format this.

```yaml
  "AWS::IAM::Policy" :
   Properties:
    PolicyName: String
    PolicyDocument: JSON
    Groups: [ String ]
    Users: [ String ]
    Roles: [ String ]
```
