### ISSUE TITLE
aws_types.aws AWS::SQS::Queue missing property QueueName: String

### ISSUE THREAD

**Issue by yumpy** [stevenjack/cfndsl#108]
`aws_types.aws` is missing `QueueName: String` from Properties.

it should be able to support

```ruby
  
  Queue(:queueEvents) {
    QueueName QUEUE_EVENTS_NAME
    VisibilityTimeout "30"
  }

```
suggested fix: 
```yaml
  "AWS::SQS::Queue" :
    Properties:
     VisibilityTimeout: String
     QueueName: String
    Attributes:
     Arn: String
     QueueName: String
```
