### ISSUE TITLE
Load balancer with access log

### ISSUE THREAD

**Issue by EsteeTan** [stevenjack/cfndsl#138]
Hi, just want to know if we can set up load balancer with access log using cfndsl? I cant find it in the examples provided. Thanks in advance!

**Comment by yumpy** [comment]
Hi @EsteeTan 

you can try this to enable access logs

```
    Resource(:elbPublic) do
      Type('AWS::ElasticLoadBalancing::LoadBalancer')
      ...
      Property('AccessLoggingPolicy',
               {
                   EmitInterval: 5,
                   Enabled: true,
                   S3BucketName: LOG_BUCKET_NAME,
                   S3BucketPrefix: ''
               }
      )
      ...
    end
```

full example resource here :

```
    Resource(:elbPublic) do
      Type('AWS::ElasticLoadBalancing::LoadBalancer')
      Property('Policies',
               [
                   {
                       Attributes: [
                           {
                               Name: 'ProxyProtocol',
                               Value: 'true'
                           }
                       ],
                       InstancePorts: [80, 443],
                       PolicyName: 'ELB-ProxyProtocol-policy',
                       PolicyType: 'ProxyProtocolPolicyType'
                   }
               ])
      Property('Subnets', [Ref(:snPublicA), Ref(:snPublicB)])
      Property('AccessLoggingPolicy',
               {
                   EmitInterval: 5,
                   Enabled: true,
                   S3BucketName: LOG_BUCKET_NAME,
                   S3BucketPrefix: ''
               })
      Property('ConnectionDrainingPolicy',
               {
                   Enabled: true,
                   Timeout: 300
               })
      Property('ConnectionSettings', {IdleTimeout: 60})
      Property('CrossZone', 'true')
      Property('HealthCheck',
               {
                   HealthyThreshold: 6,
                   Interval: 15,
                   Target: 'TCP:80',
                   Timeout: 5,
                   UnhealthyThreshold: 2
               })
      Property('SecurityGroups', [Ref(:sgELBPublic)])
      Property('Listeners',
               [
                   {
                       InstancePort: 80,
                       InstanceProtocol: 'HTTP',
                       LoadBalancerPort: 80,
                       Protocol: 'HTTP'
                   },
                   {
                       InstancePort: 80,
                       InstanceProtocol: 'HTTP',
                       LoadBalancerPort: 443,
                       PolicyNames: ['ELBSecurityPolicy-2015-05'],
                       Protocol: 'HTTPS',
                       SSLCertificateId: PUBLIC_SSL_CERTIFICATE_ID
                   }
               ])
    end
```

**Comment by EsteeTan** [comment]
How about using the cfndsl (ruby format)?

I tried something like this (see below) but kept getting error
	AccessLoggingPolicy({
	   "EmitInterval" => 5,
	   "Enabled" => true,
	   "S3BucketName" => "bucketname",
	   "S3BucketPrefix" => "bucketprefix"
	})

**Comment by yumpy** [comment]
AccessLoggingPolicy  is not yet listed in ```aws_types.yaml``` for the LoadBalancer so I don't think you can do it that way at the moment.

```yaml
  "AWS::ElasticLoadBalancing::LoadBalancer" :
   Properties:
    AvailabilityZones: [String]
    CrossZone: Boolean
    HealthCheck: HealthCheck
    Instances: [String]
    Listeners: [ Listener ]
    AppCookieStickinessPolicy: AppCookieStickinessPolicy
    LBCookieStickinessPolicy:  LBCookieStickinessPolicy
    Scheme: String
    SecurityGroups: [ String ]
    Subnets: [ String ]
    ConnectionDrainingPolicy: ConnectionDrainingPolicy
    ConnectionSettings: ConnectionSettings
    LoadBalancerName: String
    Policies: [ ElasticLoadBalancingPolicy ]
   Attributes:
    CanonicalHostedZoneName: String
    CanonicalGostedZoneNameID: String
    DNSName: String
    SourceSecurityGroup.GroupName: String
    SourceSecurityGroup.OwnerAlias: String
```
